<!-- nav -->
<div id="nav">
<span class="nav_items_s"><a href="#home" class="nav_items<?php if($nav == 0) { echo '-b';}; ?>">Home</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="#services" class="nav_items<?php if($nav == 1) { echo '-b';}; ?>">Services</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="#about" class="nav_items<?php if($nav == 2) { echo '-b';}; ?>">About</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="#portfolio" class="nav_items<?php if($nav == 3) { echo '-b';}; ?>">Portfolio</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="#contact" class="nav_items<?php if($nav == 4) { echo '-b';}; ?>">Contact</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="#seminars" class="nav_items<?php if($nav == 5) { echo '-b';}; ?>">Seminars</span>
</div>
<?php // ends main_head and wrap ?>
</div>
</div>