<!-- nav -->
<div id="nav">
<a href="home" href="#home" class="nav_items<?php if($nav == 0) { echo '-b';}; ?>">Home</a>
<a href="home" href="#services" class="nav_items<?php if($nav == 1) { echo '-b';}; ?>">Services</a>
<a href="home" href="#about" class="nav_items<?php if($nav == 2) { echo '-b';}; ?>">About</a>
<a href="home" href="#portfolio" class="nav_items<?php if($nav == 3) { echo '-b';}; ?>">Portfolio</a>
<a href="home" href="#contact" class="nav_items<?php if($nav == 4) { echo '-b';}; ?>">Contact</a>
<a href="home" href="#seminars" class="nav_items<?php if($nav == 5) { echo '-b';}; ?>">Seminars</a>
</div>
<?php // ends main_head and wrap ?>
</div>
</div>