<!-- nav -->
<div id="nav">
<span class="nav_items_s"><a href="index.php" class="nav_items<?php if($nav == 0) { echo '-b';}; ?>">Home</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="services.php" class="nav_items<?php if($nav == 1) { echo '-b';}; ?>">Services</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="about.php" class="nav_items<?php if($nav == 2) { echo '-b';}; ?>">About</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="portfolio.php" class="nav_items<?php if($nav == 3) { echo '-b';}; ?>">Portfolio</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="contact.php" class="nav_items<?php if($nav == 4) { echo '-b';}; ?>">Contact</a></span><span class="nav_line"></span>
<span class="nav_items_s"><a href="seminars.php" class="nav_items<?php if($nav == 5) { echo '-b';}; ?>">Seminars</a></span>
</div>
<?php // ends main_head and wrap ?>
</div>
</div>
<div id="main">
<div id="main_wrap">